name: CI
on: 
  push:
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    permissions: 
      packages: write
      security-events: write
      id-token: write
  
    steps:
      - name: Obtendo o código fonte
        uses: actions/checkout@v4.1.2

      - name: Configurando o Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '20.x'

      - name: Instalação do ESLint
        run: npm install -g eslint

      - name: Execução do ESLint
        run: eslint 
        working-directory: ./src

      - name: Criação da pasta resultados
        run: mkdir resultados

      - name: Validação do Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./src/Dockerfile
          no-fail: true
          output-file: resultados/hadolint-docker-fileimage-results.sarif
          format: sarif

      - uses: actions/upload-artifact@v4
        with:
          path: resultados
          name: erros
        
      - name: Docker Login
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USR }}
          password: ${{ secrets.DOCKERHUB_PWD }}
        
      - name: Docker build 
        uses: docker/build-push-action@v5.3.0
        with: 
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            michelsimao/conversao-temperatura-aula:v${{ github.run_number }}
            michelsimao/conversao-temperatura-aula:latest

      - name: Scan da Imagem Docker
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: michelsimao/conversao-temperatura-aula:v${{ github.run_number }}
          format: 'sarif'
          exit-code: 0
          scan-type: 'image'
          severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
          output: 'resultados/trivy-dockerimage-results.sarif'

      - name: Upload arquivo sarif
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: resultados
          category: ferramentas
  
